---

- name: Create the Foreman Organziations
  theforeman.foreman.organization:
      username: "{{ foreman_admin_username }}"
      password: "{{ foreman_admin_password }}"
      server_url: "{{ foreman_server_url }}"
      name: "{{ item.name }}"
      state: present
      validate_certs: false
  loop: "{{ orgs }}"
  tags:
    - orgs
    - organizations